#!/bin/bash
# PDF2UBL Virtual Environment Activation Script

echo "Activating PDF2UBL virtual environment..."
source venv/bin/activate

echo "PDF2UBL environment activated!"
echo "Available commands:"
echo ""
echo "📄 BASIC USAGE:"
echo "  python3 -m src.pdf2ubl.cli --help                    - Show help"
echo "  python3 -m src.pdf2ubl.cli convert invoice.pdf      - Convert PDF to UBL XML"
echo "  python3 -m src.pdf2ubl.cli extract invoice.pdf      - Preview extraction (no XML)"
echo ""
echo "📁 BATCH PROCESSING:"
echo "  python3 -m src.pdf2ubl.cli batch ./invoices/         - Convert all PDFs in directory"
echo "  python3 -m src.pdf2ubl.cli batch ./invoices/ -o ./output/ - Batch with output dir"
echo ""
echo "🔧 TEMPLATES:"
echo "  python3 -m src.pdf2ubl.cli template list             - List all templates"
echo "  python3 -m src.pdf2ubl.cli template show generic_nl  - Show template details"
echo "  python3 -m src.pdf2ubl.cli template create           - Create new template"
echo "  python3 -m src.pdf2ubl.cli template delete <id>      - Delete template"
echo ""
echo "🧪 TESTING:"
echo "  python3 -m src.pdf2ubl.cli test                      - Generate test UBL XML"
echo "  python3 test_all_invoices.py                         - Test all invoices"
echo ""
echo "💡 EXAMPLES:"
echo "  python3 -m src.pdf2ubl.cli convert invoice.pdf -t generic_nl"
echo "  python3 -m src.pdf2ubl.cli convert invoice.pdf -s \"ProServe\""
echo "  python3 -m src.pdf2ubl.cli batch ./invoices/ --continue-on-error"
echo ""
echo "Note: generic_nl template is used by default for all Dutch invoices"
echo ""
echo "To deactivate: deactivate"
echo ""