version: '3.8'

services:
  pdf2ubl:
    build: .
    container_name: pdf2ubl
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - /tmp/pdf2ubl-uploads:/tmp
    environment:
      - PDF2UBL_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s